// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1NjJOcnam9lNwD23WfAQNoXyJhmolg24',
    appId: '1:934197175528:web:671890dd100a70afd7155d',
    messagingSenderId: '934197175528',
    projectId: 'bookstore-9355d',
    authDomain: 'bookstore-9355d.firebaseapp.com',
    databaseURL: 'https://bookstore-9355d-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-9355d.appspot.com',
    measurementId: 'G-DRPV1CXRPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITpmRsBq46Td0gAoCyrEmHQtYkvwgjHM',
    appId: '1:934197175528:android:8e3582be1b2c054cd7155d',
    messagingSenderId: '934197175528',
    projectId: 'bookstore-9355d',
    databaseURL: 'https://bookstore-9355d-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-9355d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5KDA8lvpp9SYAU7gW9R_mUCw0jZu9_k',
    appId: '1:934197175528:ios:7b191c29ac73f274d7155d',
    messagingSenderId: '934197175528',
    projectId: 'bookstore-9355d',
    databaseURL: 'https://bookstore-9355d-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-9355d.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5KDA8lvpp9SYAU7gW9R_mUCw0jZu9_k',
    appId: '1:934197175528:ios:7b191c29ac73f274d7155d',
    messagingSenderId: '934197175528',
    projectId: 'bookstore-9355d',
    databaseURL: 'https://bookstore-9355d-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-9355d.appspot.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1NjJOcnam9lNwD23WfAQNoXyJhmolg24',
    appId: '1:934197175528:web:f80b1968a3f08974d7155d',
    messagingSenderId: '934197175528',
    projectId: 'bookstore-9355d',
    authDomain: 'bookstore-9355d.firebaseapp.com',
    databaseURL: 'https://bookstore-9355d-default-rtdb.firebaseio.com',
    storageBucket: 'bookstore-9355d.appspot.com',
    measurementId: 'G-2B338ZH6GD',
  );
}


